CREATE TABLE IF NOT EXISTS `wp_reservation` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`reservation_date`  int(10) NULL  COMMENT '日期',
`morning_count`  char(50) NULL  DEFAULT 30 COMMENT '上午放号数',
`afternoon_count`  char(50) NULL  DEFAULT 30 COMMENT '下午放号数',
`c_time`  int(10) NULL  COMMENT '创建日期',
`manager_id`  int(10) NULL  DEFAULT 0 COMMENT '管理员ID',
`token`  varchar(255) NULL  COMMENT 'Token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('reservation','每天放号','0','','1','["reservation_date","morning_count","afternoon_count"]','1:基础','','','','','reservation_date|day_format:30%日期\r\nmorning_count:15%上午放号数\r\nafternoon_count:15%下午放号数\r\nids:40%操作:lists?reservation_id=[id]&_controller=ReservationNumber&_addons=Reservation|查看预约情况,[DELETE]|删除','20','','','1436236287','1436255291','1','MyISAM','Reservation');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reservation_date','日期','int(10) NULL','date','','','1','','0','reservation','1','1','1436236546','1436236546','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('morning_count','上午放号数','char(50) NULL','select','30','','1','30:30\r\n31:31\r\n32:32\r\n33:33\r\n34:34\r\n35:35\r\n36:36\r\n37:37\r\n38:38\r\n39:39\r\n40:40\r\n41:41\r\n42:42\r\n43:43\r\n44:44\r\n45:45\r\n46:46\r\n47:47\r\n48:48\r\n49:49\r\n50:50\r\n51:51\r\n52:52\r\n53:53\r\n54:54\r\n55:55\r\n56:56\r\n57:57\r\n58:58\r\n59:59\r\n60:60','0','reservation','0','1','1436249878','1436236781','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('afternoon_count','下午放号数','char(50) NULL','select','30','','1','30:30\r\n31:31\r\n32:32\r\n33:33\r\n34:34\r\n35:35\r\n36:36\r\n37:37\r\n38:38\r\n39:39\r\n40:40\r\n41:41\r\n42:42\r\n43:43\r\n44:44\r\n45:45\r\n46:46\r\n47:47\r\n48:48\r\n49:49\r\n50:50\r\n51:51\r\n52:52\r\n53:53\r\n54:54\r\n55:55\r\n56:56\r\n57:57\r\n58:58\r\n59:59\r\n60:60','0','reservation','0','1','1436249892','1436236849','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('c_time','创建日期','int(10) NULL','date','','','0','','0','reservation','0','1','1436236906','1436236906','','3','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('manager_id','管理员ID','int(10) NULL','num','0','','0','','0','reservation','0','1','1436251279','1436251263','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NULL','string','','','0','','0','reservation','0','1','1436251320','1436251320','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


CREATE TABLE IF NOT EXISTS `wp_reservation_number` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`reservation_id`  int(10) NULL  COMMENT '日期ID',
`use_time`  int(10) NULL  COMMENT '提交预约的时间',
`desc`  text NULL  COMMENT '病症描述',
`name`  varchar(255) NULL  COMMENT '姓名',
`phone`  varchar(255) NULL  COMMENT '手机号',
`is_use`  int(10) NULL  DEFAULT 0 COMMENT '是否预约',
`type`  int(10) NULL  COMMENT '上午/下午',
`reservation_date`  int(10) NULL  COMMENT '预约日期',
`reservation_num`  varchar(255) NULL  COMMENT '预约号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('reservation_number','预约号','0','','1','["reservation_date","type","is_use","phone","name","desc","use_time"]','1:基础','','','','','type|get_name_by_status:10%上午/下午\r\nreservation_num:15%预约号\r\nis_use|get_name_by_status:10%是否预约\r\nname:11%姓名\r\nphone:12%手机号\r\ndesc:20%病症描述\r\nuse_time:12%提交预约时间\r\nids:10%操作:[EDIT]|编辑,[DELETE]|删除','20','','','1436237723','1436256435','1','MyISAM','Reservation');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reservation_id','日期ID','int(10) NULL','num','','','0','','0','reservation_number','0','1','1436251378','1436251378','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('use_time','提交预约的时间','int(10) NULL','datetime','','','0','','0','reservation_number','0','1','1436256904','1436238953','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('desc','病症描述','text NULL','textarea','','','1','','0','reservation_number','0','1','1436238865','1436238865','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('name','姓名','varchar(255) NULL','string','','','1','','0','reservation_number','0','1','1436238841','1436238841','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','手机号','varchar(255) NULL','string','','','1','','0','reservation_number','0','1','1436254005','1436238816','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_use','是否预约','int(10) NULL','radio','0','','1','0:未预约\r\n1:已预约','0','reservation_number','0','1','1436256933','1436238780','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('type','上午/下午','int(10) NULL','radio','','','1','0:上午\r\n1:下午','0','reservation_number','0','1','1436256997','1436238743','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reservation_date','预约日期','int(10) NULL','date','','','0','','0','reservation_number','0','1','1436258926','1436238697','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reservation_num','预约号','varchar(255) NULL','string','','','0','','0','reservation_number','0','1','1436256148','1436253089','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


