CREATE TABLE IF NOT EXISTS `wp_shop_coupon` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(30) NULL  COMMENT '优惠券名称',
`num`  int(10) NULL  DEFAULT 0 COMMENT '发放量',
`money`  decimal(11,2) NULL  COMMENT '面值',
`money_max`  decimal(11,2) NULL  DEFAULT 0 COMMENT '最大面值',
`is_money_rand`  tinyint(2) NULL  DEFAULT 0 COMMENT '面值是否随机',
`order_money`  decimal(11,2) NULL  DEFAULT 0 COMMENT '订单金额',
`limit_num`  char(50) NULL  DEFAULT 0 COMMENT '每人限领',
`start_time`  int(10) NULL  COMMENT '生效时间',
`end_time`  int(10) NULL  COMMENT '过期时间',
`limit_goods`  tinyint(2) NULL  DEFAULT 0 COMMENT '可适用商品',
`limit_goods_ids`  varchar(100) NULL  COMMENT '指定的商品',
`is_market_price`  tinyint(2) NULL  DEFAULT 0 COMMENT '仅原价购买商品时可用 ',
`content`  text NULL  COMMENT '使用说明',
`status`  tinyint(2) NULL  DEFAULT 1 COMMENT '状态',
`collect_count`  int(10) NULL  DEFAULT 0 COMMENT '领取数',
`use_count`  int(10) NULL  DEFAULT 0 COMMENT '已使用数',
`manager_id`  int(10) NULL  COMMENT '管理员ID',
`token`  varchar(100) NULL  COMMENT 'Token',
`cTime`  int(10) NULL  COMMENT '创建时间',
`member`  varchar(100) NULL  DEFAULT 0 COMMENT '选择人群',
`type`  char(10) NULL  DEFAULT 0 COMMENT '优惠券类型',
`is_del`  int(10) NULL  DEFAULT 0 COMMENT '是否删除',
`is_show`  int(10) NULL  DEFAULT 0 COMMENT '在手机端是否显示',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('shop_coupon','代金券','0','','1','["title","num","money","money_max","is_money_rand","order_money","limit_num","start_time","end_time","limit_goods","limit_goods_ids","is_market_price","content","member","type"]','1:基础','','','','','title:代金券名称\r\nmoney:面值\r\nlimit_num:领取限制\r\nstart_time:有效期\r\ncollect_count:已领取\r\nuse_count:已使用\r\nids:操作:preview?id=[id]|预览,lists?_controller=Sn&target_id=[id]|领取记录,sncode_lists?id=[id]|核销记录,[EDIT]|编辑,[DELETE]|删除,index&_addons=ShopCoupon&_controller=Wap&id=[id]|复制链接','10','title:请输入代金券名称搜索','','1442390631','1445565340','1','MyISAM','ShopCoupon');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','优惠券名称','varchar(30) NULL','string','','','1','','0','shop_coupon','1','1','1442390791','1442390791','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('num','发放量','int(10) NULL','num','0','','1','','0','shop_coupon','1','1','1442390822','1442390822','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('money','面值','decimal(11,2) NULL','num','','','1','','0','shop_coupon','1','1','1442390916','1442390916','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('money_max','最大面值','decimal(11,2) NULL','num','0','','1','','0','shop_coupon','0','1','1444650857','1442390963','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_money_rand','面值是否随机','tinyint(2) NULL','bool','0','','1','0:否|money_max@hide\r\n1:是|money_max@show','0','shop_coupon','0','1','1442391067','1442391067','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('order_money','订单金额','decimal(11,2) NULL','num','0','满多少可以使用，0表示不限制','1','','0','shop_coupon','0','1','1442391194','1442391194','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('limit_num','每人限领','char(50) NULL','select','0','','1','0:不限张\r\n1:1张\r\n2:2张\r\n3:3张\r\n4:4张\r\n5:5张\r\n10:10张','0','shop_coupon','0','1','1442391505','1442391505','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('start_time','生效时间','int(10) NULL','datetime','','','1','','0','shop_coupon','1','1','1442391577','1442391534','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('end_time','过期时间','int(10) NULL','datetime','','','1','','0','shop_coupon','1','1','1442391587','1442391560','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('limit_goods','可适用商品','tinyint(2) NULL','bool','0','','1','0:全店适用|limit_gooods_ids@hide\r\n1:指定商品适用|limit_gooods_ids@show','0','shop_coupon','0','1','1442391793','1442391793','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('limit_goods_ids','指定的商品','varchar(100) NULL','string','','','1','','0','shop_coupon','0','1','1442391948','1442391948','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_market_price','仅原价购买商品时可用 ','tinyint(2) NULL','bool','0','','1','0:否\r\n1:是','0','shop_coupon','0','1','1442392119','1442392119','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','使用说明','text NULL','textarea','','','1','','0','shop_coupon','0','1','1442392183','1442392183','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','tinyint(2) NULL','bool','1','','0','0:失效\r\n1:正常','0','shop_coupon','0','1','1442392723','1442392723','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('collect_count','领取数','int(10) NULL','num','0','','0','','0','shop_coupon','0','1','1442392753','1442392753','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('use_count','已使用数','int(10) NULL','num','0','','0','','0','shop_coupon','0','1','1442392790','1442392790','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('manager_id','管理员ID','int(10) NULL','num','','','0','','0','shop_coupon','0','1','1442392818','1442392818','','3','','regex','get_mid','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(100) NULL','string','','','0','','0','shop_coupon','0','1','1442392843','1442392843','','3','','regex','get_token','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','创建时间','int(10) NULL','datetime','','','0','','0','shop_coupon','0','1','1442392869','1442392869','','3','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('member','选择人群','varchar(100) NULL','checkbox','0','','1','0:所有用户\r\n-1:所有会员','0','shop_coupon','0','1','1446101088','1444620516','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('type','优惠券类型','char(10) NULL','radio','0','','1','0:优惠券\r\n1:代金券\r\n2:礼品券','0','shop_coupon','0','1','1444649770','1444649770','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_del','是否删除','int(10) NULL','num','0','','0','','0','shop_coupon','0','1','1446119655','1446119655','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_show','在手机端是否显示','int(10) NULL','num','0','在手机端会员卡领取代金券页面中是否显示','1','0:不显示\r\n1:显示','0','shop_coupon','0','1','1450086914','1450086883','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


