CREATE TABLE IF NOT EXISTS `wp_we_media` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`cate_id`  varchar(100) NULL  DEFAULT 0 COMMENT '分类',
`title`  varchar(255) NULL  COMMENT '标题',
`cover_id`  int(10) UNSIGNED NULL  COMMENT '图片',
`music`  int(10) UNSIGNED NULL  COMMENT '背景音乐',
`intro`  text NULL  COMMENT '简介',
`content`  text  NULL  COMMENT '内容',
`init_view_count`  int(10) NULL  DEFAULT 0 COMMENT '初始化阅读数',
`init_digg_count`  int(10) NULL  DEFAULT 0 COMMENT '初始化点赞数',
`is_top`  tinyint(2) NULL  DEFAULT 0 COMMENT '列表置顶',
`ad_top_type`  tinyint(2) NULL  DEFAULT 0 COMMENT '顶部广告类型',
`ad_top_img`  int(10) UNSIGNED NULL  COMMENT '广告图片',
`ad_top_url`  varchar(255) NULL  COMMENT '广告链接',
`ad_bottom_type`  tinyint(2) NULL  DEFAULT 0 COMMENT '底部广告类型',
`ad_bottom_img`  int(10) UNSIGNED NULL  COMMENT '底部广告图片',
`ad_bottom_url`  varchar(255) NULL  COMMENT '底部广告链接',
`author`  varchar(100) NULL  COMMENT '作者名',
`author_url_type`  tinyint(2) NULL  DEFAULT 0 COMMENT '点击作者跳转到',
`author_url`  varchar(255) NULL  COMMENT '自定义链接',
`view_count`  int(10) NULL  DEFAULT 0 COMMENT '阅读数',
`digg_count`  int(10) NULL  DEFAULT 0 COMMENT '点赞数',
`comment_count`  int(10) NULL  DEFAULT 0 COMMENT '评论数',
`uid`  int(10) NULL  COMMENT '用户ID',
`ad_top_count`  int(10) NULL  DEFAULT 0 COMMENT '顶部广告跳转数',
`ad_bottom_count`  int(10) NULL  DEFAULT 0 COMMENT '底部广告跳转数',
`ad_author_count`  int(10) NULL  DEFAULT 0 COMMENT '作者栏跳转数',
`cTime`  int(10) NULL  COMMENT '创建时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('we_media','自媒体中心','0','','1','["cate_id","title","cover_id","music","intro","content","init_view_count","init_digg_count","is_top","ad_top_type","ad_top_img","ad_top_url","ad_bottom_type","ad_bottom_img","ad_bottom_url","author_url_type","author_url"]','1:基础','','','','','cover_id:主图\r\ntitle:标题\r\ncTime:创建时间\r\nview_count:阅读数\r\nview_count:阅读数\r\ndigg_count:点赞数\r\ncomment_count:评论数\r\nad_top_count:顶部广告跳转数\r\nad_bottom_count:底部广告跳转数\r\nad_author_count:作者栏跳转数\r\n ad_top_img:预览码\r\nid:操作:detail?id=[id]|详细地址,[EDIT]|编辑,[DELETE]|删除','10','title:请输入标题','','1441019906','1441531673','1','MyISAM','WeMedia');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cate_id','分类','varchar(100) NULL','dynamic_select','0','','1','table=we_media_category&value_field=id','0','we_media','1','1','1441520087','1441020109','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','标题','varchar(255) NULL','string','','','1','','0','we_media','1','1','1441020152','1441020152','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cover_id','图片','int(10) UNSIGNED NULL','picture','','','1','','0','we_media','1','1','1441020176','1441020176','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('music','背景音乐','int(10) UNSIGNED NULL','file','','','1','','0','we_media','0','1','1441020225','1441020225','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('intro','简介','text NULL','textarea','','','1','','0','we_media','1','1','1441020258','1441020249','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','内容','text  NULL','editor','','','1','','0','we_media','1','1','1441020288','1441020288','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('init_view_count','初始化阅读数','int(10) NULL','num','0','','1','','0','we_media','0','1','1441020318','1441020318','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('init_digg_count','初始化点赞数','int(10) NULL','num','0','','1','','0','we_media','0','1','1441020355','1441020355','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('is_top','列表置顶','tinyint(2) NULL','bool','0','','1','0:不置顶\r\n1:置顶','0','we_media','0','1','1441020416','1441020416','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_top_type','顶部广告类型','tinyint(2) NULL','bool','0','','1','0:无广告|ad_top_img@hide,ad_top_url@hide\r\n1:我的名片|ad_top_img@hide,ad_top_url@hide\r\n2:自定义|ad_top_img@show,ad_top_url@show','0','we_media','0','1','1441020851','1441020736','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_top_img','广告图片','int(10) UNSIGNED NULL','picture','','','1','','0','we_media','0','1','1441020773','1441020773','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_top_url','广告链接','varchar(255) NULL','string','','','1','','0','we_media','0','1','1441020799','1441020799','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_bottom_type','底部广告类型','tinyint(2) NULL','bool','0','','1','0:无广告|ad_bottom_img@hide,ad_bottom_url@hide\r\n1:我的名片|ad_bottom_img@hide,ad_bottom_url@hide\r\n2:自定义|ad_bottom_img@show,ad_bottom_url@show','0','we_media','0','1','1441020962','1441020919','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_bottom_img','底部广告图片','int(10) UNSIGNED NULL','picture','','','1','','0','we_media','0','1','1441021001','1441021001','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_bottom_url','底部广告链接','varchar(255) NULL','string','','','1','','0','we_media','0','1','1441021037','1441021037','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('author','作者名','varchar(100) NULL','string','','','0','','0','we_media','0','1','1441022764','1441021091','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('author_url_type','点击作者跳转到','tinyint(2) NULL','bool','0','','1','0:作者的名片|author_url@hide\r\n1:自定义链接|author_url@show','0','we_media','0','1','1441021268','1441021205','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('author_url','自定义链接','varchar(255) NULL','string','','','1','','0','we_media','0','1','1441021239','1441021239','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('view_count','阅读数','int(10) NULL','num','0','','0','','0','we_media','0','1','1441021330','1441021321','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('digg_count','点赞数','int(10) NULL','num','0','','0','','0','we_media','0','1','1441021934','1441021354','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('comment_count','评论数','int(10) NULL','num','0','','0','','0','we_media','0','1','1441021437','1441021429','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','用户ID','int(10) NULL','num','','','0','','0','we_media','0','1','1441160721','1441160721','','3','','regex','get_mid','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_top_count','顶部广告跳转数','int(10) NULL','num','0','','0','','0','we_media','0','1','1441162215','1441162215','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_bottom_count','底部广告跳转数','int(10) NULL','num','0','','0','','0','we_media','0','1','1441162247','1441162247','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_author_count','作者栏跳转数','int(10) NULL','num','0','','0','','0','we_media','0','1','1441162291','1441162291','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','创建时间','int(10) NULL','datetime','','','0','','0','we_media','0','1','1441175906','1441175906','','3','','regex','time','1','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


CREATE TABLE IF NOT EXISTS `wp_we_media_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(50) NULL  COMMENT '分类名',
`uid`  int(10) NULL  COMMENT '用户ID',
`manager_id`  int(10) NULL  DEFAULT 0 COMMENT 'manager_id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('we_media_category','自媒体分类','0','','1','["title"]','1:基础','','','','','id:编号\r\ntitle:分类名\r\nids:操作:[EDIT]|编辑,[DELETE]|删除','10','title','','1441021795','1441022597','1','MyISAM','WeMedia');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','分类名','varchar(50) NULL','string','','','1','','0','we_media_category','1','1','1441021834','1441021826','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','用户ID','int(10) NULL','num','','','0','','0','we_media_category','0','1','1441160762','1441160762','','3','','regex','get_mid','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('manager_id','manager_id','int(10) NULL','num','0','','0','','0','we_media_category','0','1','1441527014','1441524944','','3','','regex','get_mid','1','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


CREATE TABLE IF NOT EXISTS `wp_we_media_digg` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`uid`  int(10) NULL  COMMENT '用户ID',
`media_id`  int(10) NULL  COMMENT '内容ID',
`cTime`  int(10) NULL  COMMENT '点赞时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`,`addon`) VALUES ('we_media_digg','点赞','0','','1','','1:基础','','','','','','10','','','1441176756','1441176756','1','MyISAM','WeMedia');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','用户ID','int(10) NULL','num','','','0','','0','we_media_digg','0','1','1441176785','1441176785','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('media_id','内容ID','int(10) NULL','num','','','0','','0','we_media_digg','0','1','1441176807','1441176807','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`model_name`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','点赞时间','int(10) NULL','datetime','','','0','','0','we_media_digg','0','1','1441176829','1441176829','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;


